#!/bin/bash

COMPOSE_ROOT=/boot/config/plugins/compose.manager/projects
COMPOSE_WRAPPER=/usr/local/emhttp/plugins/compose.manager/scripts/compose.sh

for dir in $COMPOSE_ROOT/*; do
    if [ -d "$dir" ]; then
        if [ -f "$dir/compose.yml" ]; then
            if [ -f "$dir/autostart" ]; then
                if [ 'true' == "$(cat $dir/autostart)" ]; then
                    # echo "$dir/compose.yml"
                    logger "Starting compose stack: $(cat $dir/Name)"
                    $COMPOSE_WRAPPER up "$dir/compose.yml" "$(cat $dir/Name)" > /dev/null &
                fi
            fi
        fi
    fi
done

wait