#!/bin/bash

COMPOSE_ROOT=/boot/config/plugins/compose.manager/projects
COMPOSE_WRAPPER=/usr/local/emhttp/plugins/compose.manager/scripts/compose.sh

for dir in $COMPOSE_ROOT/*; do
    if [ -d "$dir" ]; then
        if [ -f "$dir/docker-compose.yml" ]; then
            # echo "$dir/docker-compose.yml"
            logger "Stopping compose stack: $(cat $dir/name)"
            $COMPOSE_WRAPPER stop "$dir" "$(cat $dir/name)" > /dev/null &
        fi
    fi
done

wait
